# Generated by Django 2.0.3 on 2018-03-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180315_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('femail', 'Female')], max_length=32, null=True),
        ),
    ]
