# Generated by Django 2.0.3 on 2018-03-23 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='poster',
            new_name='image',
        ),
        migrations.AddField(
            model_name='movie',
            name='actor',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='naver_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='pub_date',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='subtitle',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='user_rating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=512),
        ),
    ]
