# Generated by Django 2.0.3 on 2018-03-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20180326_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='naver_link',
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='company',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='nation',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='pub_date',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
