# Generated by Django 2.0.3 on 2018-04-03 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_movielike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplereview',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simple_reviews', to='movies.Movie'),
        ),
    ]
