# Generated by Django 2.0.3 on 2018-04-03 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_auto_20180403_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielike',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='movies.Movie'),
        ),
        migrations.AlterField(
            model_name='simplereviewlike',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='movies.SimpleReview'),
        ),
    ]
